### ISSUE TITLE
connector() ignores NOT_PROXY_HOSTS when PHP is invoked from shell

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#14]
### Describe the bug
Connections to internal webservers called over https get an error message from the systems http proxy.

### To reproduce
1. Create a PHP script that utilized the Mapbender connector() class to display web content.
1. Call the script on web content of a server in the internal network that is listed in mapbender.confs `NOT_PROXY_HOSTS`
1. See error in the response that comes from the fw proxy

### Expected behavior
Wenn das Zielsystem in der mapbender.conf in den `NOT_PROXY_HOSTS` aufgeführt ist soll der FW Proxy nicht verwendet werden.
Die Angefragte Adresse soll erfolgreich ausgeliefert werden.

### System
* Debian Stretch
* Behind a forward proxy with authentication

### Additional context
If the script is called over the webserver it works.
The request only fails if the PHP script is called directly over PHP from the shell.

Mapbender monitoring of certain services is effected by this behavior as the monitoring is invoked by calling PHP directly.

**Comment by holsandre** [comment]
Sven:
We should look into the PHP configuration as this usually differs for shell and httpd.

**Comment by SvenTUM** [comment]
I separated the connector and tried to recreate the bug. It did not occur. 
The monitoring issue stated in _Additional context_ still occurs, but must have some other cause.
