### ISSUE TITLE
AdV Specification for alternateTitle

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#19]
To follow the attached specifications the possibility to populate the field `MD_Metadata/identificationInfo[1]/SV_ServiceIdentification/citation/*/alternateTitle` should be added.

**Comment by SvenTUM** [comment]
Hi @armin11!
Could you have a look at this and reply if it's gonna be implemented?

**Comment by lvgl-ma** [comment]
Hi @armin11,
could you plan it for 2023?

**Comment by lvgl-cs** [comment]
Hi @armin11,
see attached the redmine ticket referring to the adv-document we discussed this morning.
[geoportal-4714.pdf](https://github.com/mrmap-community/Mapbender2.8/files/13041930/geoportal-4714.pdf)

**Comment by lvgl-cs** [comment]
I am also attaching the adv-document because it's linked to our redmine server. 
[AdV-Produktspezifikation AdV-MIS, Version 1.0.1.pdf](https://github.com/mrmap-community/Mapbender2.8/files/13042047/AdV-Produktspezifikation.AdV-MIS.Version.1.0.1.pdf) (page 8)

**Comment by armin11** [comment]
The possibility to edit the alternateTitle element is implemented for wms/wfs/dataset - we need some further logic to export them in the export handlers - mod_layerISOMetadata.php, mod_featuretypeISOMetadata.php, mod_dataISOMetadata.php ;-)

**Comment by armin11** [comment]
The export handler are adopted - please test it ;-) https://github.com/mrmap-community/Mapbender2.8/commit/577c5add0b427675a13a0ed8692edc4678a5ef57

**Comment by lvgl-cs** [comment]
Hi Armin, thanks a lot, most parts seem to be working perfectly fine. Minor problems were reported by testers regarding the metadata for downloadservices (predefined atom) where the population of the field is missing and it would be great if it could also be populated to the services when dataset metadata is coupled based on URLs.
