### ISSUE TITLE
digitize - not wanted scroll after zoomToFeature

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#2]
after clicking an feature in the digitize tree,
the body outside of the ifram scrolls down ...

this is fatal for us, because we deactivated scrolling in general if mapviewer is loaded

**Comment by karlbrink** [comment]
the problem occurs on more events then the mentioned above in chrome.

i found a solution for our environment.

now i add position:fixed to the body element if mapviewer-opened, so the jquery event stuff inside the iframes is not able to scroll the body outside the iframes.

my fallback is still a scrollToTop button at the bottom of the page (appears automatically if the body is scrolled however at least 50px)

i close this issue for now
