### ISSUE TITLE
session expire leads to infinite gui reload

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#29]
Original: https://git.osgeo.org/gitea/GDI-RP/GeoPortal.rlp/issues/250

@karlo wrote:

sometimes it happens that the mapbender session expires.

then an alertbox pop up and informs you about that - you shoud click ok to reload.
 
After the click and the reload of the GUI - the alertbox comes again.... there it is - the loop

the only chance to get a valid session again is ... delete browser cache!!

Reproduce:

Open Map-Viewer in Browser and leave it untouched for e.g. 30 minutes

First Test:

vi /data/mapbender/lib/ajax.php
//add fileload after class_Mapbender.php
require_once(dirname(FILE) . “/../core/globalSettings.php”);

First Test fails!! no change in the behavior.

**Comment by armin11** [comment]
https://github.com/mrmap-community/Mapbender2.8/commit/75f9af798e2fb221f76711819e9be8c49a1eb576 fixed the behaviour ;-)
