### ISSUE TITLE
Service Metadata: Mishandling of sublayers in metadata editor after updating the service

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#37]
### Describe the bug ###

After updating a service with a non-flat layer structure the ordering of those layers in the administrative GUI for editing WMS metadata is messy.

### To Reproduce ###

1. Log on to your system with an administrative account
2. Update an WMS with multiple levels of sublayers
3. Open the WMS metadata editor
4. See error in wrongfully ordered layers

### Expected behavior ###

The ordering should look just like the ordering of the layers in the service. 

### Screenshots ###

![Screenshot of falsy behaviour](https://git.osgeo.org/gitea/attachments/9795ed07-67ff-4963-9385-251ca5154e50)

_Image 1: Messy layer ordering_

![Screenshot off expected behaviour](https://git.osgeo.org/gitea/attachments/138c37a2-7f15-42cf-9872-522a4bccb843)

_Image 2: Expected layer ordering_

**Comment by SvenTUM** [comment]
This has been tested in our system and seems to be resolved.
