### ISSUE TITLE
digitize - click on kml-tree-object events

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#4]
after clicking an object in the kml-tree the viewer navigates to the position of the geometry and opens the edit-context-menu

for a better user experience - in our opinion - it should only navigate to the object and not activate the edit function - this is already possible with an extra button.

Our usecase is to use the kmltree functionality to build an small information system without the need of publishing an wms service (e.g. to navigate to the diffrent objects (parcels) and then use the feature info to gather more informations)

Example:
we built an gui with activated kml-tree after gui load (toggleModule target kmlTree_Button) including WMC with digitized objects and available application metadata
https://www.geoportal.hessen.de/mapbender/frames/index.php?gui_id=gui_liebenau&WMC=4149

**Comment by holsandre** [comment]
karlo:


can be solved with editing file: mapbender/http/plugins/mb_digitize_widget.php

comment out line 300
//editObject($(this), null)(e);

disadvantage:
the object is not highlighted anymore - highlighting comes with the editObject function

**Comment by holsandre** [comment]
Sven:



We might want to ask some users of the feature if they’d want to have focos or edit as the default action when just clicking on a feature in the KML tree.

I don’t use the tool, so I don’t have a strong opinion on this.

If you replace the line

                        editObject($(this), null)(e);

with the following you should get the selected feature highlighted in the KML tree, if that’s what you want...

                        $(this).addClass('kmltree-selected').siblings().removeClass('kmltree-selected');

**Comment by karlbrink** [comment]
@SvenTUM your solution is okay, but if an object is selected - the submenu-entry "edit" is active too - so if you want to edit an selected object you have to deactivate and activate again using the "edit" button in the submenu.
i just stay with my solution without highlighting
and close the issue for now
