### ISSUE TITLE
Give back WFS Capabilities URLs in searchInterface

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#48]
For resources, that are available via WFS Interfaces, the WFS URLs should be given in the reslt list. The URLs are already available in the mod_showMetadata.php module and may easily be published. Should it be done, if the user have permission to access a featuretype or always?

**Comment by armin11** [comment]
Should be fixed with https://github.com/mrmap-community/Mapbender2.8/commit/dd259e6512f55f08676131465a9f480dcc5b526b#diff-02bfedf01d3753e660e831ba894808f58cb587eeab11a896b9c733a1347f9edb
