### ISSUE TITLE
Allow editing of temporal extent for application metadata

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#53]
Same as https://git.osgeo.org/gitea/armin11/GeoPortal.rlp/issues/153. It is a mapbender28 issue and I will close the GeoPortal.rlp one ;-) .

**Comment by holsandre** [comment]
Is this Issue solved with f08148139e ?
https://git.osgeo.org/gitea/GDI-RP/Mapbender2.8/commit/f08148139e

**Comment by armin11** [comment]
Yes it is now possible to define a temporal extent for application metadata - but does this make sense? ;-) - it will be good to have a use case
