### ISSUE TITLE
digitize - Point symbol for digitized objects are not shown in Firefox

### ISSUE THREAD

**Issue by holsandre** [mrmap-community/Mapbender2.8#54]
There was a problem when building the new wmc loader module end of 2019. The wmc that are loaded may already have kml / geojson layer. To support this behaviour, the mb_digitize_widget.php module was altered, so that the icons are loaded some time later:
line 259: setTimeout("var kml = $(#mapframe1).data(kml)", 2000);
After this workaround, the point symbols are not shown any longer.
Solve this problem - maybe the icons should be loaded in an independet way.

**Comment by holsandre** [comment]
Sven:


I temporarily removed the setTimeout in our system to restore the digitizing functionality.

The fix should be done in the WMC slider, as it’s non essential while the digitizing functionality is.



I’ll open a PR on this.

If the WMC slider doesn’t work any more it can be disabled and should be fixed without messing up other features.

**Comment by holsandre** [comment]
karlo:
the point symbols are still not drawn in the map nor in the kml-tree

**Comment by holsandre** [comment]
karlo:


ok....
vi /data/mapbender/http/plugins/mb_digitize_widget.php
line: 174

if i change the relative path in the ajax call to following:

$.ajax({
	url: 'https://' + location.hostname + '/mapbender/extensions/makiicons/selection.json',
	type: 'GET',
	dataType: 'json',
	timeout: 2000,
	success: function(data) {
	    icons = data;
	    var kml = $('#mapframe1').data('kml');
	    kml.icons = icons;
	}
});

the icons are displayed in firefox....

...but then the WAF block all further calls

**Comment by holsandre** [comment]
Sven:


I can confirm this fixes the issue for Firefox. In this file you might use JavaScript and embedded PHP, so this would also work:

        var create = function() {
            $.ajax({
                url:  '<?php echo MAPBENDER_PATH; ?>/extensions/makiicons/selection.json',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    icons = data;
                    var kml = $('#mapframe1').data('kml');
                    kml.icons = icons;
                },
                timeout: 2000
            });

I’d prefer your draft though. I’d suggest using window.location.href.

        var create = function() {
            $.ajax({
                url: 'https://' + location.hostname.href + '/mapbender/extensions/makiicons/selection.json',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    icons = data;
                    var kml = $('#mapframe1').data('kml');
                    kml.icons = icons;
                },
                timeout: 2000
            });

I tested it with Firefox 88.0.1 (64-Bit) and Chrome 92.0.4512.6 and it worked in both browsers. I didn’t have issues with the WAF.

I’d consider configuring the WAF task not nessesarily related to this repository.

**Comment by SvenTUM** [comment]
I commented in OSGEO Gitea, as I didn't yet update the link yet...

---

The bug only seems to occur under the following circumstances

1. using Firefox
1. using Mapviewer from / or /search/ within an iframe (relative paths won't match)
1. using the Modern / HE GUI

in all other cases it seems to work fine for me.

**Comment by SvenTUM** [comment]
OK. It took me over 2 hours of work, but I believe I fixed this. 
It'll be deployed in our staging the next update and if it work's I'll let you know. 

All the changes are squashed in [this commit](https://git.osgeo.org/gitea/LVGL/Mapbender2.8/commit/fa4db94cf9f15074207e5620c244f8fedab00de2). 
**Note** that the changes in the SQL files need to be configured in all running instances.

It seriously is a pain to find bugs that are not in the actual code base but in this ugly androgyne between database and code base.

**Comment by SvenTUM** [comment]
The fixes seem to work. The changes have been deployed in our staging instance. 

**Note** 
Some of the SQL fixes were worsening the situation before fixing it. The `display: none;` statements should be `display: block;`.

**Comment by karlbrink** [comment]
add url('fonts/icomoon.woff?sxe5mz') format('woff'), again

**Comment by karlbrink** [comment]
did you test the standard-gui after this fix?
if so, we could accept the PR
