### ISSUE TITLE
atomfeedclient - address search is pointing to geoportal.rlp hardcoded

### ISSUE THREAD

**Issue by karlbrink** [mrmap-community/Mapbender2.8#67]
the url of the gezetteer should be pointing to the location.hostname instead e.g. 
gazetteerUrl: "https://" + location.hostname + "/mapbender/geoportal/gaz_geom_mobile.php?"

**Comment by SvenTUM** [comment]
I don't really know what this is about. Can you specify what you did, what happened and what you expected to happen?

**Comment by karlbrink** [comment]
> 
> 
> I don't really know what this is about. Can you specify what you did, what happened and what you expected to happen?

armin11 implemented an address search in the atomfeed client a few weeks ago in /javascripts/mb_downloadFeedClient.php. But he used a link to the gaz_geom_mobile.php under www.geoportal.rlp.de - i commited a relative variant of the link into the branch 67_....
