### ISSUE TITLE
digitize - loading saved data empty list

### ISSUE THREAD

**Issue by karlbrink** [mrmap-community/Mapbender2.8#69]
# normal behavior
You load the modern GUI - open the digitize tool - add new element - 
then you shoul see this:
![grafik](https://user-images.githubusercontent.com/85093749/123933222-75382b00-d992-11eb-9479-835d96f7106c.png)

# problem
if you are signed in and proceed like above you see just this:
![grafik](https://user-images.githubusercontent.com/85093749/123933541-c6e0b580-d992-11eb-9878-8d2847e75509.png)

# expected
in the classic GUI it is working as expected:
![grafik](https://user-images.githubusercontent.com/85093749/123934387-86356c00-d993-11eb-8dab-a4c1c9473500.png)

# ideas
if the user you are logged in has no saved WMC, the problem does also **not** occur.
so if we compare the usecases - signed in or not - has saved wmc or not - in the classic gui the difference is at least in the styling of the datatable.

**perhaps there are just used diffrent versions of the datatables jquery plugin** the one used in the modern gui is perhaps just incompatible

**Comment by karlbrink** [comment]
pls doublecheck someone:

yes! there was a difference in the used jquery datatables version.
i changed the modern gui like this:
![grafik](https://user-images.githubusercontent.com/85093749/123941352-5d64a500-d99a-11eb-98ae-e5424b43766b.png)

1. the modul is called: **jq_datatables**
2. change the modul-path to: `../extensions/dataTables-1.7.5/media/js/jquery.dataTables.min.js,../extensions/dataTables-1.7.5/extras/TableTools-2.0.0/media/js/TableTools.min.js`
3. go to the elementVar section of the modul jq_datatables and change the value of defaultCSS to `../extensions/dataTables-1.7.5/media/css/demo_table_jui.css`

**Comment by SvenTUM** [comment]
I could recreate it and had the same values and behavior.
