### ISSUE TITLE
Stored Dataset Metadata break INSPIRE Validation of Services

### ISSUE THREAD

**Issue by SvenTUM** [mrmap-community/Mapbender2.8#70]
# Status Quo

When a service (e.g. WMS) is registered and coupled with a dataset metadata record via CSW the CSW will be requested and the metadata will be stored in the Mapbender database. This not only includes metadata on the metadata record, but the CSW response itself. 

When exporting the service metadata using **mod_layerISOMetadata.php** the dataset metadata will be referenced like this:

```xml
<srv:operatesOn xlink:href="https://[FQDN]/mapbender/php/mod_dataISOMetadata.php?outputFormat=iso19139&id=[UUID]" uuidref="[UUIDref]"/>
```

The URL found in the `href` attribute will be valided. Currently **mod_dataISOMetadata.php** will return the stored record from the Mapbender database. **This breaks validation!**

# Requirement

The exported service metadata **_must not_** reference an out of date record!

**Comment by armin11** [comment]
Fixed with https://github.com/mrmap-community/Mapbender2.8/commit/805c2cb51162425ab192e796f36a10e4b0d896f6
