### ISSUE TITLE
WMS metadataeditor - bug in layertree 

### ISSUE THREAD

**Issue by armin11** [mrmap-community/Mapbender2.8#90]
The layertree in the metadataeditor is generated from a mptt model. The model is calculated in https://github.com/mrmap-community/Mapbender2.8/blob/master/http/plugins/mb_metadata_server.php#L604 . The generation of left and right attributes for the tree does not work. For example the wms https://maps.dwd.de/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities has 2 folders below the root element. In the metadataeditor only one folder is shown. The other folder is somewhere in the first one. The generation of the attributes should be fixed or another algorithm should be used ;-) .
See the attached two screenshots
![Bildschirmfoto von 2022-01-03 09-12-24](https://user-images.githubusercontent.com/1188234/147910284-6df1beaf-afb4-4a5e-a4f2-01b11f3828f3.png)
![Bildschirmfoto von 2022-01-03 09-11-56](https://user-images.githubusercontent.com/1188234/147910316-577b521c-4b5a-4cb6-8e35-af1c2940f2f0.png)

**Comment by armin11** [comment]
Now it works like it should do ;-)

![Bildschirmfoto von 2022-01-03 14-25-49](https://user-images.githubusercontent.com/1188234/147935693-c5d6a794-75b2-4415-9688-cd683fbe3414.png)

**Comment by SvenTUM** [comment]
Is this issue a duplicate of #37 ?

**Comment by armin11** [comment]
Maybe - please check if the fix works for you ;-)
