### ISSUE TITLE
Add helptext with examples for coords lookup module

### ISSUE THREAD

**Issue by armin11** [mrmap-community/Mapbender2.8#92]
https://github.com/mrmap-community/Mapbender2.8/blob/master/http/javascripts/mod_coordsLookup.php

Helptexts with examples may be helpful ;-) - distinguish between projected coordinates and geographic ones - maybe the class_crs.php can be used from server side (pull some info from the epsg registry)

**Comment by muqit-zoarder** [comment]
Helptext as placeholder information has been updated in mapviewer Toolbox for "Coordinate Search" tool. 

Steps:

1) In coordsLookup module we have added x and y placeholder values for each srs value inside projections variable. Please see the screenshot below: 


![bild_2](https://user-images.githubusercontent.com/98881990/211566370-8155fe9d-71f0-45c0-bdb9-e400218ac025.PNG)


2) mod_coordsLookup.php file has been updated to achieve the goal.

3) Duplicate value from dropdown menue of "Spatial Reference System" has been removed and gave the label name for Spatial Reference System.

4) Placeholder helptext for both longitude and latitude has been added for each dropdown srs value which produce helptext by clicking on seperate srs value.
(please see below screensot)

![bild_1](https://user-images.githubusercontent.com/98881990/211564931-71feb1d8-4776-4332-96cd-6afc4bb7890f.PNG)

5) Removed the Perimeter label from dropdown menue and gave the label name as Perimeter.

**Comment by karlbrink** [comment]
see also: https://test.geoportal.hessen.de/map?gui_id=Geoportal-Hessen-2019
