### ISSUE TITLE
mod_linkedDataProxy - Inconsistent Coordinate Axis for Collection and Item View

### ISSUE THREAD

**Issue by SvenTUM** [mrmap-community/Mapbender2.8#98]
## Describe the bug

The coordinate axis is swapped for a particular collection when accessing one of the items.

## To Reproduce

1. Visit [the collection page](https://geoportal.saarland.de/spatial-objects/320/collections/ALKIS_Sanierungsgebiete:Sanierungsgebiete/items?&f=html)
2. Note the map representation
3. Click on a [link for one of the items](https://geoportal.saarland.de/spatial-objects/320/collections/ALKIS_Sanierungsgebiete:Sanierungsgebiete/items/Sanierungsgebiete.1?f=html)
4. Note the feature coordinates are swapped

## Expected behavior

Both representations should have the same axis order.

## Screenshots

![clipboard-202205181318-ftjzf](https://user-images.githubusercontent.com/8211898/169039143-d2f2c04a-a442-4889-8eac-659e4a33a770.png)

![clipboard-202205181319-mcbwc](https://user-images.githubusercontent.com/8211898/169039187-1b46318b-d551-4521-b942-6f5d9672188c.png)

**Comment by SvenTUM** [comment]
Maybe the filtered request looks for (and successfully finds) a higher WFS version in the background and therefor has the swapped coordinate axis in the result.

**Comment by armin11** [comment]
as i remember it is a problem of the esri wfs :-( - please test a mapserver based one and compare the results

**Comment by SvenTUM** [comment]
The questionable WFS certainly is an ArcGIS Server WFS. I don't know of any MapServer WFS in out registry.

Something obviously is done differently for the two API calls. If it's an actual bug in the AGS WFS implementation we could close this issue.

**Comment by lvgl-cs** [comment]
This indeed was an issue with the ArcGIS server and can be closed due to that.
